services:
  mysql:
    image: mysql:oraclelinux9
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

    # Salud: El backend esperará a que MySQL esté realmente LISTO, no solo iniciado
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASS}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - turnos-network

  appmic-turnosbackend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: turnos-system-appmic-turnosbackend:1.0
    container_name: appmic-turnosbackend
    restart: always
    ports:
      - "3300:${PORT}"
    environment:
      PORT: ${PORT}
      DB_HOST: mysql # Usamos el nombre del servicio como host
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    # Límites de recursos: Evita que un error bloquee tu Ubuntu
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    depends_on:
      mysql:
        condition: service_healthy # Solo arranca si el healthcheck de MySQL pasa
    networks:
      - turnos-network

networks:
  turnos-network:
    driver: bridge

volumes:
  mysql-data: