services:
  appmic-turnosbackend:
    build:
      context: ./
      dockerfile: Dockerfile.dev   # aquÃ­ usas el Dockerfile con DevTools
    volumes:
      - ./src:/app/src
      - ./target:/app/target
    environment:
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:${PORT}"
    restart: always
    networks:
      - turnos-network
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:oraclelinux9   # misma imagen que producciÃ³n
    container_name: mysql
    restart: always
    ports:
      - "3306:${DB_PORT}"
    volumes:
      - mysql-data:/var/lib/mysql   # ðŸ”‘ mismo volumen que prod
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASS}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - turnos-network

networks:
  turnos-network:
    driver: bridge

volumes:
  mysql-data:   # ðŸ”‘ volumen compartido entre dev y prod