services:
  turnosbackend:
    build:
      context: ../../ # ruta del proyecto turnos-system
      dockerfile: infra/docker/Dockerfile.prod   # aqu√≠ usas el multi-stage
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "3300:${PORT}"
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - turnos-network

  mysql:
    image: mysql:oraclelinux9
    container_name: mysql
    restart: always
    ports:
      - "3306:${DB_PORT}"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASS}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - turnos-network

networks:
  turnos-network:
    driver: bridge

volumes:
  mysql-data:
    name: turnos-system_mysql-data